version: "3.6"
services:
  main_control:
    # image: "ghcr.io/roboeagles4828/developer-environment:7"
    image: "ghcr.io/roboeagles4828/jetson:4"
    network_mode: "host"
    privileged: true
    environment:
      - ROS_DOMAIN_ID=0
      - FASTRTPS_DEFAULT_PROFILES_FILE=/usr/local/share/middleware_profiles/rtps_udp_profile.xml
    deploy:
      restart_policy:
        delay: 2s
        max_attempts: 3
        window: 120s
    entrypoint: ["/bin/bash", "-c", "/opt/workspace/docker/jetson/entrypoint.sh"]
    working_dir: /opt/workspace
    user: admin
    volumes:
    - ${HOME}/rift2024:/opt/workspace
  zed_cam:
    image: ghcr.io/roboeagles4828/jetson-zed:2
    network_mode: "host"
    privileged: true
    runtime: nvidia
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/usr/local/share/middleware_profiles/rtps_udp_profile.xml
      - ROS_NAMESPACE=real
    volumes:
      - /usr/bin/tegrastats:/usr/bin/tegrastats
      - /tmp/argus_socket:/tmp/argus_socket
      - /usr/local/cuda-11.4/targets/aarch64-linux/lib/libcusolver.so.11:/usr/local/cuda-11.4/targets/aarch64-linux/lib/libcusolver.so.11
      - /usr/local/cuda-11.4/targets/aarch64-linux/lib/libcusparse.so.11:/usr/local/cuda-11.4/targets/aarch64-linux/lib/libcusparse.so.11
      - /usr/local/cuda-11.4/targets/aarch64-linux/lib/libcurand.so.10:/usr/local/cuda-11.4/targets/aarch64-linux/lib/libcurand.so.10
      - /usr/local/cuda-11.4/targets/aarch64-linux/lib/libnvToolsExt.so:/usr/local/cuda-11.4/targets/aarch64-linux/lib/libnvToolsExt.so
      - /usr/local/cuda-11.4/targets/aarch64-linux/lib/libcupti.so.11.4:/usr/local/cuda-11.4/targets/aarch64-linux/lib/libcupti.so.11.4
      - /usr/local/cuda-11.4/targets/aarch64-linux/include:/usr/local/cuda-11.4/targets/aarch64-linux/include
      - /usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra
      - /usr/src/jetson_multimedia_api:/usr/src/jetson_multimedia_api
      - /opt/nvidia/nsight-systems-cli:/opt/nvidia/nsight-systems-cli
      - /opt/nvidia/vpi2:/opt/nvidia/vpi2
      - /usr/share/vpi2:/usr/share/vpi2
      - /dev/*:/dev/*
      - ${HOME}/rift2024/src/edna_bringup/config/zed_config-common-custom-box.yaml:/root/ros2_ws/src/zed-ros2-wrapper/zed_wrapper/config/common.yaml
      - ${HOME}/rift2024/model.engine:/root/ros2_ws/model.engine
      - ${HOME}/rift2024/scripts/config/SN39192289.conf:/usr/local/zed/settings/SN39192289.conf
      - ${HOME}/rift2024/src/edna_bringup/launch/zed2i.launch.py:/root/ros2_ws/src/zed-ros2-wrapper/zed_wrapper/launch/zed2i.launch.py
    depends_on:
      - main_control
    deploy:
      resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
    command: ["ros2", "launch", "zed_wrapper", "zed2i.launch.py"]

    

