#!/bin/bash
# Get pip
sudo apt-get install -y python3-pip

echo -e "\e[93mInstalling ROS Dependencies\e[0m"

# Preload workspace dependencies
cd /tmp && 
    sudo apt-get update -y && 
    rosdep update --rosdistro=humble &&
    rosdep install --from-paths src --ignore-src -r -y &&
    sudo rm -rf /tmp/src
