<?xml version = "1.0"?>
<robot xmlns:xacro = "http://www.ros.org/wiki/xacro">

    <xacro:property name="stow_hardstop_length" value="0.0508" />
    <xacro:property name="stow_hardstop_width" value="0.235" />
    <xacro:property name="stow_hardstop_height" value="0.32" />
    <xacro:property name="lower_bearing_distance" value = ".076" />

    <xacro:macro name = "stow_hardstop" params = "parent *origin">
        <link name = "stow_hardstop_link">
            <xacro:inertial_box mass = "2.494758035" x = "${stow_hardstop_length}" y = "${stow_hardstop_width}" z = "${stow_hardstop_height}">
                <origin xyz = "0 0 ${stow_hardstop_height/2}" rpy = "0 0 0"/>
            </xacro:inertial_box>
            <visual>
                <origin xyz = "0 0 0" rpy = "0 0 ${pi/2}"/>
                <geometry>
                    <mesh filename="package://rift_description/meshes/RiftStowHardstop.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name = "silver"/>
            </visual>
            <collision>
                <origin xyz = "0 0 0" rpy = "0 0 0"/>
                <geometry>
                    <box size = "${stow_hardstop_length} ${stow_hardstop_width} ${stow_hardstop_height}"/>
                </geometry>
            </collision>
        </link>
        <joint name = "stow_hardstop_joint" type = "fixed">
            <parent link = "${parent}"/>
            <child link = "stow_hardstop_link"/>
            <xacro:insert_block name = "origin"/>
        </joint>
    </xacro:macro>
</robot>