#!/usr/bin/bash
python_path="/isaac-sim/python.sh"
scripts_path="/root/edna/isaac/Eaglegym/eaglegym/scripts/rlgames_train.py"
gym_path="/root/edna/isaac/Eaglegym"

setup() {
    echo "Setting up gym..."
    isaac $python_path -m pip uninstall -y eaglegym
    isaac $python_path -m pip install -e $gym_path
}

setup-help() {
    echo "Usage: gym setup"
    echo "  "
    echo "Description:"
    echo "  Installs eaglegym and required dependencies"
    echo "  "
}

train-help() {
    echo "Usage: gym train [<argument>=<value>]..."
    echo "  "
    echo "Arguments:"
    echo "  task=<task>               -- Selects the task to train"
    echo "  headless=<bool>           -- Selects whether to run headless or not"
    echo "  test=<bool>               -- Selects whether to run test mode or not"
    echo "  checkpoint=<path>         -- Selects the checkpoint to load (usually located in Eaglegym/eaglegym/runs/<task>/nn/<checkpoint>.pth)"
    echo "  enable_livestream=<bool>  -- Selects whether to enable livestream or not (requires Omniverse Streaming Client)"
    echo "  "
    echo "Description:"
    echo "  Trains the selected task with the selected arguments"
    echo "  "
    echo "Examples:"
    echo "  gym train task=SwerveK headless=True"
    echo "  "
}

train() {
    echo "Training..."
    isaac $python_path $scripts_path ${@:2} headless=True
}

test() {
    echo "Testing..."
    isaac $python_path $scripts_path ${@:2} test=True num_envs=36
}

help() {
    echo "Usage: gym (setup | train)"
    echo "  "
    echo "Arguments:"
    echo "  setup   -- Sets up gym"
    echo "  train   -- Trains selected gym task"
    echo "  "
}

case $1 in 
    "setup")
        case $2 in
            "--help")
                setup-help
            ;;

            "-h")
                setup-help
            ;;

            *)
                setup
            ;;
        esac
    ;;

    "train")
        case $2 in
            "--help")
                train-help
            ;;

            "-h")
                train-help
            ;;

            "")
                echo "No arguments specified, task is required!!!"
                exit 1
            ;;
            
            *)
                train $@
            ;;
        esac
    ;;

    "test")
        case $2 in
            "--help")
                train-help
            ;;

            "-h")
                train-help
            ;;

            "")
                echo "No arguments specified, task is required!!!"
                exit 1
            ;;
            
            *)
                test $@
            ;;
        esac
    ;;
    
    *)
        echo "Unknown option: \"$1\""
        help
        ;;
esac